server:
  error:
    include-messages: always
  logging:
    level:
      root: INFO
      com.viktorkuts: DEBUG
      org.hibernate.sql: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:postgresql://pg_cs/customers-db
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none
    config:
      activate:
        on-profile: docker
  sql:
    init:
      platform: psql
      mode: always
