server:
  error:
    include-messages: always
  logging:
    level:
      root: INFO
      com.viktorkuts: DEBUG
      org.hibernate.sql: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customers-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
    driver-class-name: org.h2.Driver
    username: user
    password: pwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always
server:
  port: 7001

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:postgresql://pg_cs/customers-db
    username: user
    password: pwd
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: psql
      mode: always

server:
  port: 8080
